### PR TITLE
View docs

### PR DESCRIPTION
**Pull request by HaoZeke**
The html docs are really nicely formatted but there were no clear instructions to using them. So I added some.

### CODE REVIEW

**Comment by lmhale99** [comment]
Hi @HaoZeke,

Sorry about taking so long to reply, but I was working on hosting the docs at a [permanent location](https://www.ctcms.nist.gov/potentials/atomman), which just went live.

Let me know if you feel your commits are still needed.

**Comment by HaoZeke** [comment]
Oh, I'm glad they're up permanently! This might be still useful for people who are often offline (traveling).

**Comment by lmhale99** [comment]
Is there an advantage of installing and using yarn and browser-sync when the Python standard library has SimpleHTTPServer (for 2.7) and http.server (for 3+)?

$ python -m http.server

Then, open localhost:8000 in a browser.

**Comment by HaoZeke** [comment]
Nope, they're equivalent...

**Pull request closed without merging**
